### ISSUE TITLE
Tool broken on latest patch

### ISSUE THREAD

**Issue by Theswweet** [zchaudhry11/DeemoTools#1]
Tried to set 4K with the tool, and - as expected, perhaps - it's borked as of the latest patch. It appears that the game isn't receiving anymore support, so hopefully a quick fix will be enough going forward?

**Comment by zchaudhry11** [comment]
I haven't touched the tool since launch but it seems to be working fine for me on two different machines. Can you tell me a bit about how you're using the tool? The process should be: launch tool, launch game, alt + tab into tool to change the resolution, return to game

**Comment by Theswweet** [comment]
My bad; I thought changing from fullscreen to windowed and back in the settings was enough!
